# See https://help.apple.com/app-store-connect/#/devd274dd925

devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 11 Pro",
   "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
   "en-US",
   "de-DE",
   "es-ES"
])

clear_previous_screenshots(true)

# For more information about all available options run
# fastlane action snapshot
